camunda.bpm.admin-user:
  id: demo
  password: demo
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgree_base
    username: root
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

#datasource:
#  url: jdbc:h2:mem:testdb
#  driver-class-name: org.h2.Driver
#  username: sa
#  password:
#jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#
#datasource:
#  driver-class-name: org.postgresql.Driver
#  url: jdbc:postgresql://localhost:5432/postgree_base
#  username: s312431
#  password: 6uxe7h4u*
#  # JPA properties
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: false
#    generate-ddl: false


